// T6 Behavior Descriptions — 132 items for the BIM Masterwheel

export const behaviorDescriptions = [
  "Raised tone, sharp posture, subtle physical threat",
  "Verbal jabs or physical threat escalation",
  "Explosive outburst, harsh language, sudden movement",
  "Physical intimidation or aggression with emotional override",
  "Honest feedback, direct disagreement",
  "Firm pushback, standing ground under tension",
  "Boundary confrontation with emotional charge",
  "Direct conflict with accusatory framing",
  "Subtle assertion of control or power",
  "Power play or one-upmanship",
  "Status enforcement, cutting control",
  "Commanding dominance, override of autonomy",
  "Crossed arms, clipped tone, deflecting questions",
  "Justifying tone, rigid body, sharp rebuttal",
  "Rapid talking, sarcasm, emotionally raised",
  "Interrupting, loud rebuttal, hands thrown upward",
  "Short remark, tight smile, delayed sarcasm",
  "Intentional withdrawal, clipped dismissal",
  "Verbal jab, referencing past slight, pointed",
  "Aggressive comeback, raised voice, stare-down",
  "Shrugs, vague answers, avoids eye contact",
  "Laughs off comment, dodges accountability",
  "Sudden shift in topic, restless posture",
  "Snapping, retreating while speaking, abrupt pivot",
  "Mix of sarcasm and affection, jumpy tone",
  "Argument one moment, apology the next",
  "Wild accusations, sudden embrace, emotional whiplash",
  "Push-pull, rage-then-retreat, dramatic withdrawal",
  "Snarky jab with half-smile",
  "Baiting comment to provoke reaction",
  "Over-personal criticism disguised as humor",
  "Aggressive teasing or sarcastic challenge",
  "Avoids eye contact, goes silent",
  "Leaves room, says little or nothing",
  "Hides in phone or distraction",
  "Disappears during or after tension",
  "Quickly changes topic when conflict arises",
  "Minimizes or laughs off concern",
  "Repeatedly postpones difficult discussions",
  "Avoids triggering topics with blame-shift",
  "Plays dumb or vague to dodge accountability",
  "Uses jokes or humor to derail hard topics",
  "Redirection with a fake concern",
  "Denies or reroutes with emotional twist",
  "Backs away mid-conversation",
  "Reaches for connection while fleeing",
  "Retreats while offering reassurance",
  "Disengages while checking for approval",
  "Starts to leave, pauses mid-step",
  "Offers a reason but waits for permission",
  "Signals exit but keeps glancing back",
  "Tries to make exit look casual or passive",
  "Staggers back emotionally, can’t take input",
  "Snaps under pressure to escape interaction",
  "Frantically shuts things down or changes topic",
  "Dissolves emotionally mid-conflict",
  "Goes still, visibly unresponsive",
  "Stares forward in silence",
  "Sits motionless, refuses to move or speak",
  "Withdraws completely from interaction",
  "Looks lost or far away mid-sentence",
  "Describes event in oddly distant way",
  "Uses metaphor or story to talk around the event",
  "Describes body or experience as \"not real\"",
  "Freezes completely, physically or mentally",
  "Appears overwhelmed by internal shutdown",
  "Eyes wide, breath shallow, can’t respond or shift",
  "Doesn’t resist or engage, totally inert",
  "Says yes but isn’t present",
  "Nods repeatedly while looking glazed",
  "Gives agreement without clarity",
  "Cooperates while emotionally vacant",
  "Agrees quickly to calm the other",
  "Changes tone to de-escalate conflict",
  "Gives up own view for the sake of peace",
  "Makes themselves small to reduce tension",
  "Becomes emotionally enmeshed to avoid being abandoned",
  "Loses personal boundaries to maintain closeness",
  "Adopts partner’s identity or opinions without question",
  "Suppresses distress to stay merged emotionally",
  "Agrees rapidly to avoid pushback",
  "Follows instruction without questioning",
  "Sacrifices own priorities for instruction",
  "Forgets own agency in decision-making",
  "Anticipates others’ needs at the expense of own",
  "Uses kindness to maintain connection",
  "Dismisses personal discomfort to serve others",
  "Shapes responses to be liked, not truthful",
  "Soothes others to prevent escalation or discomfort",
  "Minimizes personal pain to avoid conflict",
  "Offers reassurance they don’t feel to calm others",
  "Takes blame or diffuses tension reflexively",
  "Offers care to manage own anxiety or need for closeness",
  "Steps in to fix without being asked",
  "Gives more than asked to feel secure in relationship",
  "Pushes comfort even when it isn’t wanted",
  "Prioritizes others’ needs over own as proof of love",
  "Suppresses desires to avoid disrupting connection",
  "Lives for the other’s comfort or stability",
  "Accepts imbalance as a form of loyalty",
  "Pursues constant interaction to soothe inner distress",
  "Overextends socially to feel belonging",
  "Shifts self to match group expectations",
  "Feels lost or alone without constant relational stimulation",
  "Offers emotional care or support with presence and warmth",
  "Provides comfort without overstepping",
  "Tends to someone’s state without trying to fix it",
  "Uses gentle grounding presence to co-regulate",
  "Creates connection through shared experience or vulnerability",
  "Strengthens relationships through mutual investment",
  "Builds bridges between emotional distance or misunderstandings",
  "Names shared values or commitments",
  "Shows up in challenge or vulnerability to offer steadiness",
  "Advocates or defends in moments of injustice or dismissal",
  "Offers strength or presence without overtaking",
  "Helps regulate or hold emotional weight",
  "Shields others from harm while offering warmth and care",
  "Defends through affection or closeness",
  "Steps in to protect the emotional space or boundary",
  "Uses nurturing as shield and sword simultaneously",
  "Draws firm lines in the name of care and relational health",
  "Says no with warmth and clarity",
  "Communicates tough truths to honour the relationship",
  "Holds relational standard without controlling",
  "Steps in with clarity to hold or redirect",
  "Uses strength to interrupt harm or spiral",
  "Guides someone away from destructive action with direction",
  "Combines authority and care in real-time support",
  "Offers care through proactive, structured action",
  "Takes initiative with kindness and clarity",
  "Sets direction through care, not control",
  "Moves others forward without harshness"
];
