// emotion.js — Emotion/Feeling data for T6 view mode

export const emotion = [
  "Irritation, Unease",
  "Frustration, Alert",
  "Rage, Adrenaline, Panic",
  "Fury, Blinding Threat",
  "Discomfort, Grounded Concern",
  "Frustration, Certainty",
  "Betrayal, Exasperation",
  "Injustice, Anger, Sadness",
  "Confidence, Impatience",
  "Arrogance, Ego",
  "Superiority, Frustration",
  "Hostility, Entitlement",
  "Discomfort, Shame",
  "Hurt, Frustration",
  "Embarrassment, Injustice",
  "Shame, Guilt, Overload",
  "Resentment, Caution",
  "Anger, Grudge",
  "Bitterness, Injustice",
  "Betrayal, Fury",
  "Nervousness, Avoidance",
  "Discomfort, Guilt",
  "Defensiveness, Anxiety",
  "Overwhelm, Hopelessness",
  "Anxiety, Affection",
  "Panic, Regret",
  "Fear, Abandonment",
  "Desperation, Disorganization",
  "Insecurity, Anxiety",
  "Fear, Deflection",
  "Anger, Shame",
  "Frustration, Power Struggle",
  "Tension, Discomfort",
  "Overwhelm, Fatigue",
  "Sadness, Emotional Block",
  "Panic, Emotional Freeze",
  "Hesitation, Fear",
  "Discomfort, Guilt",
  "Anxiety, Avoidance",
  "Defensiveness, Denial",
  "Guilt, Avoidance",
  "Fear of Conflict, Tension",
  "Shame, Deflection",
  "Hurt, Distance",
  "Panic, Overload",
  "Fear of Abandonment, Neediness",
  "Shame, Desperation",
  "Self-Doubt, Anxiety",
  "Indecision, Emotional Pull",
  "Guilt, Uncertainty",
  "Vulnerability, Confusion",
  "Discomfort, Escape Urge",
  "Panic, Overload, Disorientation",
  "Sensory Overload, Frustration",
  "Anxiety, Cognitive Jam",
  "Numbness, Dizziness, Disconnect",
  "Numbness, Overwhelm",
  "Exhaustion, Internal Collapse",
  "Freeze, Isolation",
  "Disconnection, Abandonment",
  "Detachment, Floaty",
  "Surreal, Ghostlike",
  "Numbness, Mental Drift",
  "Fragmentation, Dissonance",
  "Terror, Paralysis",
  "Freeze, Guilt, Pressure",
  "Panic, Helplessness",
  "Dissociation, Body Numb",
  "Disengaged, Numb",
  "Detachment, Ghosting",
  "Internal Conflict, Withdrawn",
  "Disconnection, Resignation",
  "Anxiety, Conflict-Avoidance",
  "Insecurity, Tension",
  "Guilt, Emotional Minimizing",
  "Fear, Conflict Sensitivity",
  "Terror, Loss of Self",
  "Insecurity, Self-Suppression",
  "Fear of Rejection, Fusion",
  "Anxiety, Panic, Guilt",
  "Apprehension, Deference",
  "Indecision, Powerlessness",
  "Self-Dismissal, Insecurity",
  "Shame, Confusion",
  "Fear of Disapproval, Emptiness",
  "Insecurity, Approval Seeking",
  "Self-Neglect, Unworthiness",
  "Shame, Performance Anxiety",
  "Nervousness, Placation",
  "Fear of Disapproval, Insecurity",
  "Shame, Guilt, Disconnection",
  "Embarrassment, Anxiety",
  "Fear of Rejection, Control",
  "Anxiety, Urgency",
  "Insecurity, Need for Validation",
  "Helplessness, Over-attachment",
  "Emptiness, Desperation",
  "Loneliness, Submission",
  "Anxiety, Identity Fusion",
  "Suppression, Hopeful Endurance",
  "Anxiety, Fear of Rejection",
  "FOMO, Social Anxiety",
  "Identity Diffusion, Insecurity",
  "Fear of Abandonment, Agitation",
  "Compassion, Groundedness",
  "Steady, Attuned",
  "Tenderness, Care",
  "Patience, Trust",
  "Trust, Intimacy Seeking",
  "Loyalty, Hope",
  "Vulnerability, Repair",
  "Security, Realism",
  "Commitment, Protection",
  "Righteousness, Validation",
  "Care, Reliability",
  "Empathy, Co-regulation",
  "Loyalty, Protective Anger",
  "Fierce Love, Urgency",
  "Boundary-Driven, Trust",
  "Centered Strength",
  "Respect, Intention",
  "Love, Assertiveness",
  "Integrity, Courage",
  "Safety, Value-Driven",
  "Grounded Urgency",
  "Hopeful, Anchoring",
  "Containment, Care",
  "Fierce Presence",
  "Compassion, Control",
  "Love, Attunement",
  "Protective Guidance",
  "Compassionate Drive"
];
