// quotes.js — T6 Dataset: Expression Quotes

export const quotes = [
  "Don’t push me, alright?",
  "Say that again, I dare you.",
  "Get out of my face before I lose it!",
  "You asked for this, now deal with it!",
  "That doesn’t sit right with me.",
  "No, I’m not okay with that.",
  "You crossed the line, again.",
  "Every time, you twist the truth to control me!",
  "I’ll take care of it, trust me.",
  "Let’s be real, I’m better at this than you.",
  "You're clearly not in charge here.",
  "Do it. Now. I don’t need your opinion.",
  "That’s not what I said.",
  "You always assume the worst in me.",
  "Wow, thanks for twisting my words, again.",
  "Don’t put this all on me!",
  "Oh, I’ll remember this later.",
  "Watch what happens next.",
  "Funny, you didn’t care when it was me!",
  "You’ll regret treating me like that.",
  "I’m not sure… let’s just move on.",
  "Why are we even talking about this?",
  "There’s no point in arguing, you’re always right.",
  "Whatever, it’s not like you listen anyway.",
  "You’re the worst, but don’t leave me.",
  "I hate this, don’t go.",
  "I knew you’d hurt me, you always do, I need you.",
  "Forget it! No, wait, just stay, please.",
  "What, that struck a nerve?",
  "Wow, overreact much?",
  "Some people just can’t take feedback.",
  "You’re such a victim, come on, hit back already.",
  "I don’t want to talk right now.",
  "I just… need to go.",
  "It’s nothing, really. Forget it.",
  "I can’t deal with this, I’m out.",
  "Let’s not get into that.",
  "It’s not that big of a deal.",
  "Can we just talk later? Now’s not a good time.",
  "Maybe if you weren’t so sensitive, we’d be fine.",
  "Huh? I don’t really remember that part.",
  "Let’s lighten up, it’s not like anyone died!",
  "Are you okay though? You seem off.",
  "Wow. That’s how you see it? That’s cold.",
  "I can’t do this, please stop talking.",
  "Don’t go, I can’t handle this alone!",
  "It’s fine, it’s fine, really. I just… need space.",
  "Is this okay? Should I go?",
  "Maybe I should go, or maybe we can fix it?",
  "If you want, I can just leave…",
  "I’ll go… unless you want me to stay?",
  "Well, I’ve got stuff to do… so yeah.",
  "I can’t. It’s too much. Just, no more.",
  "Stop! I told you, I can’t handle this!",
  "Let’s talk later. I’ve got other stuff anyway.",
  "I don’t even know what’s going on anymore.",
  "No response. Eyes glaze or look away.",
  "…….",
  "…….",
  "Walks out silently, slams door, disappears.",
  "Sorry… what were you saying?",
  "It’s weird, it’s like I wasn’t even there.",
  "It felt like being underwater… everything blurred.",
  "My hands weren’t even mine, like I was watching.",
  "I just… couldn’t move.",
  "I know I should say something… but I can’t.",
  "Everything in me just stopped.",
  "You could’ve yelled or hit me, I couldn’t react.",
  "Sure… whatever you say.",
  "Mhm. Yeah. Totally.",
  "Yeah, I’m fine, just tired, that’s all.",
  "I just went along with it. No idea why.",
  "It’s okay, I get it, really, no worries.",
  "Let’s not fight, I just want us to be okay.",
  "You’re probably right. I must be overreacting.",
  "I don’t want to cause trouble. Just do what you need.",
  "I’ll be whatever you need, just don’t leave.",
  "It’s okay, I don’t really have preferences.",
  "Yeah… totally, I think that too.",
  "I didn’t say anything, I didn’t want them to pull away.",
  "Okay, I’ll do it.",
  "Alright, if that’s what you want.",
  "Whatever’s easier for you.",
  "I didn’t think I had a choice.",
  "I thought if I helped enough, they’d stay.",
  "No no, really, it’s no trouble at all!",
  "I’m totally fine, don’t worry about me.",
  "I just wanted to keep the peace.",
  "Hey, it’s fine, let’s not make this a big deal.",
  "It wasn’t that bad, really. No worries.",
  "You’re right. I was just being silly.",
  "I probably overreacted anyway. Let’s just move on.",
  "You looked tired, I made your lunch and rearranged your day.",
  "Let me just handle it, it’s easier that way.",
  "I just wanted you to know I’m always here, I got your groceries, dry cleaning, and booked your dentist.",
  "You have to eat something. Come on, just for me.",
  "I gave everything for them. It’s just who I am.",
  "It’s fine, whatever you want is fine.",
  "Their happiness is my purpose.",
  "Relationships are about sacrifice, I’m okay being last.",
  "I just want everyone to be happy, let’s do something fun!",
  "Let’s call them too! I hate leaving people out.",
  "Totally! Yeah, I’m into that too.",
  "Where is everyone? What’s going on? Why isn’t anyone replying?",
  "You don’t have to explain, I’m just here.",
  "Would it help if I stayed with you a bit longer?",
  "You don’t need to do anything, I just want you to feel seen.",
  "Take your time, I’m here, and you’re okay.",
  "What’s something you’ve never told anyone before?",
  "You matter to me, I want to grow this together.",
  "That didn’t land well, can I try again?",
  "We’re not perfect, but this bond is real.",
  "I’ve got you, you’re not going through this alone.",
  "That wasn’t fair, I saw what happened.",
  "Lean on me if you need to, I’ve got capacity today.",
  "If it gets too much, we can breathe through it together.",
  "No one gets to talk to you like that, not on my watch.",
  "Come here. Let’s make sure you feel safe before anything else.",
  "Back off, they’ve said no.",
  "I’ll be soft where it helps, and strong where it’s needed.",
  "That doesn’t work for me, and I care too much to pretend.",
  "I love you, and this is where I draw the line.",
  "I’d rather be honest than resentful.",
  "We don’t speak to each other like that, not here.",
  "That’s enough, take a breath before you wreck it.",
  "Pause. You’re better than this reaction.",
  "Let’s walk this off, we’re not doing this here.",
  "I’ve got you, and I’m not letting you spiral.",
  "You’re overwhelmed, sit, I’ll sort this.",
  "You need rest, I’ll cover dinner.",
  "Here’s what we’re doing, one step at a time.",
  "You’re stuck, I’ll walk with you ’til we’re moving again."
];
