// === thriveCounter.js — Thrive Counter Dataset ===

export const thriveCounter = [
  "I need a second, I’m starting to get tense.",
  "I’m overwhelmed, and I don’t want to hurt this.",
  "I need space before I snap.",
  "I lost it, I need to calm and repair.",
  "Let’s talk this through without heat.",
  "I want this to work, but that crossed a line.",
  "I care, but this hurts. I need space and honesty.",
  "This cycle breaks me. I need truth, not power.",
  "Say that again — I dare you.",
  "I value your role. Let’s lead together.",
  "We both matter, I don’t want a war.",
  "I’m overpowering, I need to hear, not steamroll.",
  "Let me try again, I want to be clearer.",
  "I feel judged, can we slow this down?",
  "I’m feeling cornered, let me explain calmly.",
  "This is hard, I want to own my part, not all of it.",
  "That stung, let’s clear it now, not carry it.",
  "This hurt, I want to name it and let it go.",
  "This matters, but revenge won’t heal it.",
  "I’m angry, I want repair, not revenge.",
  "I’m uneasy, but I’ll try to stay present.",
  "This is awkward, but I want to get it right.",
  "I’m frustrated, but let’s stay with it.",
  "I’m feeling dismissed, can we slow this down?",
  "I care, and I feel messy, can we ground together?",
  "This is confusing, let’s pause and sort it.",
  "This storm in me needs safety, I want to stay, not spiral.",
  "I’m in overload, I want connection, not chaos.",
  "I’m feeling cornered, can we keep this respectful?",
  "I don’t want to escalate, I’m trying to be heard.",
  "I’m upset, but I want repair, not a fight.",
  "I want honesty, not war games.",
  "I need a break, I’ll come back when I’m ready.",
  "I’m overstimulated, I’ll return when I’m clear.",
  "It feels like too much, can we take space together?",
  "I feel cornered, I need space to ground myself.",
  "This is uncomfortable, but I want to stay present.",
  "I hear you, I’m working on facing things directly.",
  "It’s hard, but I don’t want to keep dodging it.",
  "I feel protective, but I want to grow, not deflect.",
  "I’m nervous, but I want to own my side.",
  "I joke when I’m scared, can we talk seriously for a sec?",
  "I do care, and I also need to stay on topic.",
  "It stings, but I want to talk it through, not twist it.",
  "I want connection, but I need to calm my body first.",
  "I’m afraid, and I need to regulate before reaching out.",
  "I need a moment, and I’ll return when I feel safe again.",
  "I’m unsure, but I want to respond, not just escape.",
  "I’m torn, I care, and I need space to think.",
  "I feel unsure, I want clarity, not guessing games.",
  "I’m scared to lose this, but I want to be honest too.",
  "It’s tough, but I want to say it straight, not drift.",
  "I want to stay with this, but I need to slow everything down.",
  "I’m maxed out, I need to come down before I can speak clearly.",
  "I’m scattered, but I want to show up when I can focus.",
  "I’m fading, I want to return when I’m whole.",
  "I’m shutting down, I’ll return when I can connect again.",
  "I’m quiet because I’m overloaded, not because I don’t care.",
  "I’m here, but I need safety before I can engage again.",
  "I had to leave to protect myself, I’ll reconnect soon.",
  "I spaced out, but I’m trying to come back in.",
  "I feel far away, but I want to stay connected here.",
  "This is hard to name, but I want to stay in the room.",
  "It didn’t feel real, but I want to grow.",
  "I locked up, but I want to thaw and return.",
  "I’m not avoiding, I’m stuck. I want to soften this block.",
  "This is hard to explain, but I want to move again.",
  "I want to be safe enough to feel again.",
  "I agreed fast, but I didn’t check in with myself.",
  "I nodded, but I want to check what I actually feel.",
  "I want to respond truthfully, even if it’s messy.",
  "I disappeared to keep peace, but I want to return now.",
  "I soothed fast, but I want to stay honest and present.",
  "I want peace, but not by losing my truth.",
  "Even when unsure, I want to speak from my experience.",
  "I matter too, I want to...",
  "I’m scared, but I want to be myself with you.",
  "I want to stay connected while honouring my voice.",
  "I want to share this space, not vanish into it.",
  "My needs matter, even if I’m scared to say them.",
  "I want to say yes and mean it, not just submit.",
  "I want to be on board with you, not under you.",
  "I want ease and equality, not to disappear.",
  "My choice matters, I want to remember I can say no.",
  "I want to give from love, not fear.",
  "I love helping, but I want to be honest about my limits.",
  "My comfort matters too, I can say that gently.",
  "I want peace, but with truth, not pretense.",
  "I care about peace and what’s true for me.",
  "I can say I’m hurt and still want harmony.",
  "My feelings matter, I want to talk without walking on eggshells.",
  "Let’s understand what happened, not just skip over it.",
  "I love caring for you, when it’s truly wanted.",
  "I trust you to handle it, and I’m here if you need me.",
  "Being here is enough. I don’t have to overdo it to be loved.",
  "I want to support you, not smother you.",
  "I can love fully without losing myself.",
  "I want this to work for both of us.",
  "I can support them while also having my own needs.",
  "I can show up for you without vanishing myself.",
  "I can connect without needing to hold it all together.",
  "It’s okay to choose quiet or small, connection doesn’t mean stretch.",
  "I can stay true to myself and still feel close.",
  "I’m still whole, even when things go quiet.",
  "I’m right here with you, we’ll move through this together.",
  "I’ll stay as long as it feels good for both of us.",
  "You’re not alone. That’s enough right now.",
  "Let’s breathe through this together, no rush.",
  "Let’s really see each other, that’s where the magic is.",
  "We can both choose in, at our own pace.",
  "Even when we mess up, I still want to meet you.",
  "Let’s keep choosing each other, even when it’s messy.",
  "You don’t have to carry it all, I’m here beside you.",
  "Your experience matters, I’ll help make space for it.",
  "I can hold space, and still respect your pace.",
  "You’re safe to feel what’s here, I’m not going anywhere.",
  "You matter too much to let that slide.",
  "Before anything else, let’s make sure your heart’s okay.",
  "Saying no doesn’t need defending, I’ve got your back.",
  "Care isn’t weak, it’s powerful when rooted.",
  "Boundaries protect what we’re building.",
  "Limits are part of real closeness.",
  "I want to stay real with you, not passive.",
  "Respect is part of care.",
  "I want this to go well, let’s not burn it down.",
  "We can slow this down and still get heard.",
  "Strong love means stepping in when things break.",
  "We do this together, even when it’s hard.",
  "You can exhale, I’ve got a handle on this.",
  "Let me help you recover your bandwidth.",
  "Structure can feel like love when done right.",
  "Progress is easier with someone beside you."
];
